version: 2.1

jobs:
  setup_and_test:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: python -m unittest tests.tests_main

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup_and_test
